FROM nginx
USER root
WORKDIR /home/
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./m_server.c /home/m_server.c
COPY ./entrypoint.sh /home/entrypoint.sh
RUN apt-get update && apt-get install -y gcc spawn-fcgi libfcgi-dev 
ENTRYPOINT ["sh", "./entrypoint.sh"]

