FROM nginx
RUN apt-get update && apt-get install -y gcc spawn-fcgi libfcgi-dev && rm -rf /var/lib/apt/lists
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./m_server.c /home/m_server.c
COPY ./entrypoint.sh /home/entrypoint.sh
USER root
WORKDIR /home/
ENTRYPOINT ["sh", "./entrypoint.sh"]
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 CMD curl -f http://localhost/ || exit 1
